### ISSUE TITLE
Serverless parsing failing on a uri

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn_nag#135]
The following template (from run-end-to-end-tests.sh) throws an exception:

https://github.com/awslabs/aws-cloudformation-templates/blob/master/community/services/Lambda/SAM/template.yml

cfn-model-0.1.25/lib/cfn-model/transforms/serverless.rb:34:in `is_s3_uri?': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/erickascic/.rvm/gems/ruby-2.3.1/gems/cfn-model-0.1.25/lib/cfn-model/transforms/serverless.rb:48:in `replace_serverless_function'
	from /Users/erickascic/.rvm/gems/ruby-2.3.1/gems/cfn-model-0.1.25/lib/cfn-model/transforms/serverless.rb:11:in `block in perform_transform'
	from /Users/erickascic/.rvm/gems/ruby-2.3.1/gems/cfn-model-0.1.25/lib/cfn-model/transforms/serverless.rb:9:in `each'
	from /Users/erickascic/.rvm/gems/ruby-2.3.1/gems/cfn-model-0.1.25/lib/cfn-model/transforms/serverless.rb:9:in `perform_transform'
	from /Users/erickascic/.rvm/gems/ruby-2.3.1/gems/cfn-model-0.1.25/lib/cfn-model/parser/transform_registry.rb:20:in `perform_transforms'
	from /Users/erickascic/.rvm/gems/ruby-2.3.1/gems/cfn-model-0.1.25/lib/cfn-model/parser/cfn_parser.rb:41:in `parse'
	from /Users/erickascic/.rvm/gems/ruby-2.3.1/gems/cfn-nag-0.3.53/lib/cfn-nag/cfn_nag.rb:82:in `audit'
	from /Users/erickascic/.rvm/gems/ruby-2.3.1/gems/cfn-nag-0.3.53/bin/cfn_nag:70:in `<top (required)>'
	from /Users/erickascic/.rvm/gems/ruby-2.3.1/bin/cfn_nag:23:in `load'
	from /Users/erickascic/.rvm/gems/ruby-2.3.1/bin/cfn_nag:23:in `<main>'

**Comment by jeffb4** [comment]
Resolved by https://github.com/stelligent/cfn-model/commit/7ed6ab664af0ab5296f7e58c0847d0ce45f46420 (cfn-model `1.2.26`)
