### ISSUE TITLE
Undefined method error when using cfn_nag_scan recursively

### ISSUE THREAD

**Issue by vtpearce91** [stelligent/cfn_nag#196]
Receiving a stack trace when trying to execute a cfn_nag_scan with subfolders.

```
$ cfn_nag_scan --input-path=.
/Library/Ruby/Gems/2.3.0/gems/cfn-nag-0.3.89/lib/cfn-nag/template_discovery.rb:30:in `block in find_templates_in_directory': undefined method `match?' for "./subfolder":String (NoMethodError)
Did you mean?  match
	from /Library/Ruby/Gems/2.3.0/gems/cfn-nag-0.3.89/lib/cfn-nag/template_discovery.rb:29:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/cfn-nag-0.3.89/lib/cfn-nag/template_discovery.rb:29:in `find_templates_in_directory'
	from /Library/Ruby/Gems/2.3.0/gems/cfn-nag-0.3.89/lib/cfn-nag/template_discovery.rb:9:in `discover_templates'
	from /Library/Ruby/Gems/2.3.0/gems/cfn-nag-0.3.89/lib/cfn-nag/cfn_nag.rb:62:in `audit_aggregate_across_files'
	from /Library/Ruby/Gems/2.3.0/gems/cfn-nag-0.3.89/lib/cfn-nag/cfn_nag.rb:43:in `audit_aggregate_across_files_and_render_results'
	from /Library/Ruby/Gems/2.3.0/gems/cfn-nag-0.3.89/bin/cfn_nag_scan:108:in `<top (required)>'
	from /usr/local/bin/cfn_nag_scan:22:in `load'
	from /usr/local/bin/cfn_nag_scan:22:in `<main>'
```
where ./subfolder is a folder within the current folder.  While I've just now experienced the issue, it's apparently been around since 0.3.71.  I was running 0.3.54 but just now updated to the latest version.
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by vtpearce91** [comment]
Never mind - just realized this is a new feature of Ruby 2.4 and I've still got 2.3.

**Comment by jesseadams** [comment]
This changed as a result of a rubocop violation. If it proves painful to upgrade ruby please let us know and we can temporarily back this out for a while.
