### ISSUE TITLE
Error running Docker image in gitlab-ci

### ISSUE THREAD

**Issue by atkinsonm** [stelligent/cfn_nag#367]
Hello,

I would like to use the cfn_nag Docker image to run cfn_nag_scan as part of a GitLab CI pipeline. I receive the following error on attempting to use the image (`latest`):

```bash
/usr/local/bundle/gems/cfn-nag-0.5.4/lib/cfn-nag/cfn_nag_executor.rb:98:in `read': No such file or directory @ rb_sysopen - if [ -x /usr/local/bin/bash ]; then (Errno::ENOENT)
00:02
 	exec /usr/local/bin/bash 
 elif [ -x /usr/bin/bash ]; then
 	exec /usr/bin/bash 
 elif [ -x /bin/bash ]; then
 	exec /bin/bash 
 elif [ -x /usr/local/bin/sh ]; then
 	exec /usr/local/bin/sh 
 elif [ -x /usr/bin/sh ]; then
 	exec /usr/bin/sh 
 elif [ -x /bin/sh ]; then
 	exec /bin/sh 
 elif [ -x /busybox/sh ]; then
 	exec /busybox/sh 
 else
 	echo shell not found
 	exit 1
 fi
 	from /usr/local/bundle/gems/cfn-nag-0.5.4/lib/cfn-nag/cfn_nag_executor.rb:98:in `read_conditionally'
 	from /usr/local/bundle/gems/cfn-nag-0.5.4/lib/cfn-nag/cfn_nag_executor.rb:89:in `execute_io_options'
 	from /usr/local/bundle/gems/cfn-nag-0.5.4/lib/cfn-nag/cfn_nag_executor.rb:21:in `scan'
 	from /usr/local/bundle/gems/cfn-nag-0.5.4/bin/cfn_nag:11:in `<top (required)>'
 	from /usr/local/bundle/bin/cfn_nag:23:in `load'
 	from /usr/local/bundle/bin/cfn_nag:23:in `<main>'
```

This is roughly the command gitlab-ci is using in the backend:

`docker run --name build -i stelligent/cfn_nag < build_script`

Where `build_script` is something like `cfn_nag --version`

I'm going to keep trying to get this to work, using the [README.md](README.md#docker-container) example as a reference, but wanted to see if anyone else had worked out how to use the Docker image with GitLab CI

**Comment by pshelby** [comment]
Could you share the relevant pieces of your `.gitlab-ci.yml` file around how this job is executed?

Sorry for the long post and possible redundant info from README.md, but hopefully some of it is helpful.

It seems as if the docker container is trying to open the contents of `build_script` as a file, and throwing that IO error when it can't open `if [ -x /usr/local/bin/bash ]; then`.  When the stelligent/cfn_nag docker container is run, it's expecting arguments which would be passed to the cfn_nag CLI utility.  

I'm not too familiar with GitLab CI yet, however I was able to generate a similar error directly with docker when the input file to cfn_nag doesn't exist in the container:
```
$ docker run --name build -i stelligent/cfn_nag test_template.yml
/usr/local/bundle/gems/cfn-nag-0.5.4/lib/cfn-nag/cfn_nag_executor.rb:116:in `closed?': No such file or directory @ rb_sysopen - test_template.yml (Errno::ENOENT)
        from /usr/local/bundle/gems/cfn-nag-0.5.4/lib/cfn-nag/cfn_nag_executor.rb:116:in `argf_finished?'
        from /usr/local/bundle/gems/cfn-nag-0.5.4/lib/cfn-nag/cfn_nag_executor.rb:37:in `execute_file_or_piped_scan'
        from /usr/local/bundle/gems/cfn-nag-0.5.4/lib/cfn-nag/cfn_nag_executor.rb:29:in `scan'
        from /usr/local/bundle/gems/cfn-nag-0.5.4/bin/cfn_nag:11:in `<top (required)>'
        from /usr/local/bundle/bin/cfn_nag:23:in `load'
        from /usr/local/bundle/bin/cfn_nag:23:in `<main>'
$
```

If I share a volume with the container and point the cfn_nag process to `test_template.yml`, it works:
```
$ docker run --name build -i -v `pwd`:/data stelligent/cfn_nag /data/test_template.yml
------------------------------------------------------------
/data/test_template.yml
------------------------------------------------------------------------------------------------------------------------
| FAIL F3
|
| Resources: ["DataLakeWorkflowRole"]
| Line Numbers: [21]
|
| IAM role should not allow * action on its permissions policy
------------------------------------------------------------
| WARN W11
|
| Resources: ["DataLakeWorkflowRole"]
| Line Numbers: [21]
|
| IAM role should not allow * resource on its permissions policy
------------------------------------------------------------
| WARN W28
|
| Resources: ["DataLakeWorkflowRole"]
| Line Numbers: [21]
|
| Resource found with an explicit name, this disallows updates that require replacement of this resource

Failures count: 1
Warnings count: 2
$
```

Alternatively, I created a Dockerfile for running cfn_nag_scan and built a container from it to test.  I get very similar results from the same tests using the docker CLI.
```
$ docker build -t cfn_nag_scan -f Dockerfile-cfn_nag_scan .
Sending build context to Docker daemon  4.777MB
Step 1/4 : FROM ruby:2.5-alpine3.9@sha256:f33782620b363575ad95d19d0f0f07f7d197e9ccfee51f20df39dd33d408cdb4
sha256:f33782620b363575ad95d19d0f0f07f7d197e9ccfee51f20df39dd33d408cdb4: Pulling from library/ruby
e7c96db7181b: Already exists
622c94c90cb1: Already exists
dbd6b8b21943: Already exists
669f34de38a1: Already exists
3f52879bf30a: Already exists
Digest: sha256:f33782620b363575ad95d19d0f0f07f7d197e9ccfee51f20df39dd33d408cdb4
Status: Downloaded newer image for ruby:2.5-alpine3.9@sha256:f33782620b363575ad95d19d0f0f07f7d197e9ccfee51f20df39dd33d408cdb4
 ---> d22061a95435
Step 2/4 : RUN gem install cfn-nag
 ---> Running in 4dafaee58f3a
Successfully installed kwalify-0.7.2
Successfully installed cfn-model-0.4.14
Successfully installed multi_json-1.14.1
Successfully installed little-plugger-1.1.4
Successfully installed logging-2.2.2
Successfully installed netaddr-2.0.4
Successfully installed optimist-3.0.0
Successfully installed jmespath-1.4.0
Successfully installed aws-partitions-1.272.0
Successfully installed aws-eventstream-1.0.3
Successfully installed aws-sigv4-1.1.0
Successfully installed aws-sdk-core-3.89.1
Successfully installed aws-sdk-kms-1.29.0
Successfully installed aws-sdk-s3-1.60.2
Successfully installed lightly-0.3.2
Successfully installed cfn-nag-0.5.5
16 gems installed
Removing intermediate container 4dafaee58f3a
 ---> 0a1799702894
Step 3/4 : ENTRYPOINT ["cfn_nag_scan"]
 ---> Running in 30489dcef5a5
Removing intermediate container 30489dcef5a5
 ---> 0ac9df027271
Step 4/4 : CMD ["--help"]
 ---> Running in 4bf7f7df101c
Removing intermediate container 4bf7f7df101c
 ---> 672ac3ed09ce
Successfully built 672ac3ed09ce
Successfully tagged cfn_nag_scan:latest
$ docker run -t cfn_nag_scan
0.5.5
Options:
  -i, --input-path=<s>                               CloudFormation template to nag on or directory of templates.  Default is all *.json, *.yaml, *.yml and *.template recursively, but can be constrained by
                                                     --template-pattern
  -o, --output-format=<s>                            Format of results: [txt, json, colortxt] (default: colortxt)
  -d, --debug                                        Enable debug output
  -r, --rule-directory=<s>                           Extra rule directory
  -p, --profile-path=<s>                             Path to a profile file
  -b, --blacklist-path=<s>                           Path to a blacklist file
  -a, --parameter-values-path=<s>                    Path to a JSON file to pull Parameter values from
  -c, --condition-values-path=<s>                    Path to a JSON file to pull Condition values from
  -l, --allow-suppression, --no-allow-suppression    Allow using Metadata to suppress violations (default: true)
  -n, --print-suppression                            Emit suppressions to stderr
  -s, --isolate-custom-rule-exceptions               Isolate custom rule exceptions - just emit the exception without stack trace and keep chugging
  -t, --template-pattern=<s>                         Within the --input-path, match files to scan against this regular expression (default: ..*\.json|..*\.yaml|..*\.yml|..*\.template)
  -f, --fail-on-warnings                             Treat warnings as failing violations
  -u, --rule-repository=<s+>                         Path(s)s to rule repository to include in rule discovery
  -v, --version                                      Print version and exit
  -h, --help                                         Show this message
$ docker run -t cfn_nag_scan -i test_template.yml
Traceback (most recent call last):
        7: from /usr/local/bundle/bin/cfn_nag_scan:23:in `<main>'
        6: from /usr/local/bundle/bin/cfn_nag_scan:23:in `load'
        5: from /usr/local/bundle/gems/cfn-nag-0.5.5/bin/cfn_nag_scan:11:in `<top (required)>'
        4: from /usr/local/bundle/gems/cfn-nag-0.5.5/lib/cfn-nag/cfn_nag_executor.rb:29:in `scan'
        3: from /usr/local/bundle/gems/cfn-nag-0.5.5/lib/cfn-nag/cfn_nag_executor.rb:49:in `execute_aggregate_scan'
        2: from /usr/local/bundle/gems/cfn-nag-0.5.5/lib/cfn-nag/cfn_nag.rb:34:in `audit_aggregate_across_files_and_render_results'
        1: from /usr/local/bundle/gems/cfn-nag-0.5.5/lib/cfn-nag/cfn_nag.rb:61:in `audit_aggregate_across_files'
/usr/local/bundle/gems/cfn-nag-0.5.5/lib/cfn-nag/template_discovery.rb:14:in `discover_templates': test_template.yml is not a proper path (RuntimeError)
$ docker run -v `pwd`:/data -t cfn_nag_scan --input-path=/data/test_template.yml
------------------------------------------------------------
/data/test_template.yml
------------------------------------------------------------------------------------------------------------------------
| FAIL F3
|
| Resources: ["DataLakeWorkflowRole"]
| Line Numbers: [21]
|
| IAM role should not allow * action on its permissions policy
------------------------------------------------------------
| WARN W11
|
| Resources: ["DataLakeWorkflowRole"]
| Line Numbers: [21]
|
| IAM role should not allow * resource on its permissions policy
------------------------------------------------------------
| WARN W28
|
| Resources: ["DataLakeWorkflowRole"]
| Line Numbers: [21]
|
| Resource found with an explicit name, this disallows updates that require replacement of this resource

Failures count: 1
Warnings count: 2
$
```

**Comment by pshelby** [comment]
@atkinsonm I did some testing around this and was able to reproduce your issue.  I believe if you adjust your `.gitlab-ci.yml` file to override `entrypoint` of the stelligent/cfn_nag image to be an empty string, you can then pass the cfn_nag_scan command as you like in the GitLab CI job script.  Let me know if you need any clarifications, or feel free to close this issue if this solves your problem.

Example .gitlab-ci.yml file:
```yaml
default:
  image:
    name: stelligent/cfn_nag
    entrypoint: [""]

nag_failure:
  script:
    - cfn_nag_scan --input-path=test_template.yml

nag_success:
  script:
    - cfn_nag_scan --input-path=clean_template.yml
```

Example run against template with violations:
<img width="971" alt="image" src="https://user-images.githubusercontent.com/4969682/74381910-64494280-4dba-11ea-97db-b74b32455718.png">

Example run against clean template:
<img width="969" alt="image" src="https://user-images.githubusercontent.com/4969682/74381999-89d64c00-4dba-11ea-9406-3fd2dd365bd6.png">

**Comment by atkinsonm** [comment]
That worked! Thanks @pshelby!
