### ISSUE TITLE
Issue with version 0.5.31

### ISSUE THREAD

**Issue by lhgomes** [stelligent/cfn_nag#416]
I'm getting the following error when validating a Cloudfront distribution:

```
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-model-0.4.23/lib/cfn-model/validator/cloudformation_validator.rb:21:in `gsub': invalid byte sequence in US-ASCII (ArgumentError)
--
182 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-model-0.4.23/lib/cfn-model/validator/cloudformation_validator.rb:21:in `json_text?'
183 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-model-0.4.23/lib/cfn-model/validator/cloudformation_validator.rb:9:in `validate'
184 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-model-0.4.23/lib/cfn-model/parser/cfn_parser.rb:203:in `pre_validate_model'
185 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-model-0.4.23/lib/cfn-model/parser/cfn_parser.rb:59:in `parse_without_parameters'
186 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-model-0.4.23/lib/cfn-model/parser/cfn_parser.rb:43:in `parse'
187 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.31/lib/cfn-nag/cfn_nag.rb:86:in `audit'
188 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.31/lib/cfn-nag/cfn_nag_executor.rb:59:in `scan_file'
189 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.31/lib/cfn-nag/cfn_nag_executor.rb:38:in `execute_file_or_piped_scan'
190 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.31/lib/cfn-nag/cfn_nag_executor.rb:29:in `scan'
191 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.31/bin/cfn_nag:11:in `<top (required)>'
192 | from /root/.rbenv/versions/2.6.5/bin/cfn_nag:23:in `load'
193 | from /root/.rbenv/versions/2.6.5/bin/cfn_nag:23:in `<main>'
```

Ruby version 2.6
cfn_nag version 0.5.31

**Comment by tbuchier** [comment]
Hello,

Had same issue executing in cfn_nag in a CodeBuild (AWS CodeBuild have their default locale set to POSIX)  

Fixed it with : 
For Amazon Linux images : 
```
pre_build:
  commands:
    - export LC_ALL="en_US.utf8"
```
For Ubuntu images : 
```
pre_build:
  commands:
    - export LC_ALL="en_US.UTF-8"
    - locale-gen en_US en_US.UTF-8
    - dpkg-reconfigure locales

```
https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#troubleshooting-utf-8
