### ISSUE TITLE
cfn-nag v0.5.36 crashes on validating AWS::EC2::NetworkAclEntry without PortRange

### ISSUE THREAD

**Issue by terencet** [stelligent/cfn_nag#430]
With reference to https://github.com/stelligent/cfn_nag/blob/ee9d9234e1161eeeab4d8d5981ec782832127885/lib/cfn-nag/custom_rules/EC2NetworkAclEntryOverlappingPortsRule.rb#L46

The code is expecting a `portRange` when it validates a nacl entry, but not all nacl has that defined because it's not a required property. As per AWS documentation below.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-networkaclentry-portrange.html

When it tries to validate a nacl entry without port range it crashes with the following error.
```
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rules/EC2NetworkAclEntryOverlappingPortsRule.rb:46:in `roverlap?': undefined method `[]' for nil:NilClass (NoMethodError)
--
990 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rules/EC2NetworkAclEntryOverlappingPortsRule.rb:42:in `overlap?'
991 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rules/EC2NetworkAclEntryOverlappingPortsRule.rb:32:in `block in overlapping_port_entries'
992 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rules/EC2NetworkAclEntryOverlappingPortsRule.rb:31:in `select'
993 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rules/EC2NetworkAclEntryOverlappingPortsRule.rb:31:in `overlapping_port_entries'
994 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rules/EC2NetworkAclEntryOverlappingPortsRule.rb:68:in `violating_nacl_entries'
995 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rules/EC2NetworkAclEntryOverlappingPortsRule.rb:23:in `block in audit_impl'
996 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rules/EC2NetworkAclEntryOverlappingPortsRule.rb:22:in `each'
997 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rules/EC2NetworkAclEntryOverlappingPortsRule.rb:22:in `audit_impl'
998 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rules/base.rb:19:in `audit'
999 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rule_loader.rb:70:in `block in filter_rule_classes'
1000 | from /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/set.rb:338:in `each_key'
1001 | from /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/set.rb:338:in `each'
1002 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rule_loader.rb:63:in `filter_rule_classes'
1003 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/custom_rule_loader.rb:54:in `execute_custom_rules'
1004 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/cfn_nag.rb:90:in `audit'
1005 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/cfn_nag.rb:67:in `block in audit_aggregate_across_files'
1006 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/cfn_nag.rb:64:in `each'
1007 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/cfn_nag.rb:64:in `audit_aggregate_across_files'
1008 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/cfn_nag.rb:34:in `audit_aggregate_across_files_and_render_results'
1009 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/cfn_nag_executor.rb:49:in `execute_aggregate_scan'
1010 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/lib/cfn-nag/cfn_nag_executor.rb:29:in `scan'
1011 | from /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.36/bin/cfn_nag_scan:11:in `<top (required)>'
1012 | from /root/.rbenv/versions/2.6.5/bin/cfn_nag_scan:23:in `load'
1013 | from /root/.rbenv/versions/2.6.5/bin/cfn_nag_scan:23:in `<main>'
```

Example
```
  NetworkAclEntryInbound:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref 'SubnetCIDR'
      Egress: 'false'
      NetworkAclId: !Ref 'SubnetNetworkAcl'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: 1000
```

**Comment by erickascic** [comment]
@terencet thx for finding this.  we're on it and will have a fix out today.

**Comment by erickascic** [comment]
@terencet give 0.5.38 a go
