### ISSUE TITLE
cfn-nag 0.5.38 crashes on validating AWS::Batch::JobDefinition without ContainerProperties

### ISSUE THREAD

**Issue by kmoschkau** [stelligent/cfn_nag#432]
Referencing:
https://github.com/stelligent/cfn_nag/blob/ee9d9234e1161eeeab4d8d5981ec782832127885/lib/cfn-nag/custom_rules/BatchJobDefinitionContainerPropertiesPrivilegedRule.rb#L22

In Batch JobDefinition resources, the code expects the ContainerProperties property and within it the Privileged property, but ContainerProperties is not required per AWS documentation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html.

It also seems to fail even if these properties are included.

The following error is returned
```
C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/custom_rules/BatchJobDefinitionContainerPropertiesPrivilegedRule.rb:22:in `block in audit_impl': undefined method `[]' for nil:NilClass (NoMethodError)
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/custom_rules/BatchJobDefinitionContainerPropertiesPrivilegedRule.rb:21:in `select'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/custom_rules/BatchJobDefinitionContainerPropertiesPrivilegedRule.rb:21:in `audit_impl'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/custom_rules/base.rb:19:in `audit'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/custom_rule_loader.rb:70:in `block in filter_rule_classes'
        from C:/Software/Ruby26-x64/lib/ruby/2.6.0/set.rb:338:in `each_key'
        from C:/Software/Ruby26-x64/lib/ruby/2.6.0/set.rb:338:in `each'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/custom_rule_loader.rb:63:in `filter_rule_classes'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/custom_rule_loader.rb:54:in `execute_custom_rules'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/cfn_nag.rb:90:in `audit'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/cfn_nag.rb:67:in `block in audit_aggregate_across_files'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/cfn_nag.rb:64:in `each'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/cfn_nag.rb:64:in `audit_aggregate_across_files'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/cfn_nag.rb:34:in `audit_aggregate_across_files_and_render_results'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/cfn_nag_executor.rb:49:in `execute_aggregate_scan'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/lib/cfn-nag/cfn_nag_executor.rb:29:in `scan'
        from C:/Software/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.5.38/bin/cfn_nag_scan:11:in `<top (required)>'
        from C:/Software/Ruby26-x64/bin/cfn_nag_scan:23:in `load'
        from C:/Software/Ruby26-x64/bin/cfn_nag_scan:23:in `<main>'
```

This example should be valid according to documentation. My resource is a a bit lengthier.

```
  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: multinode
```

**Comment by erickascic** [comment]
@kmoschkau thx for taking the time to report this bug.  give 0.5.39 (just released) a go

**Comment by kmoschkau** [comment]
@erickascic Works like a charm, thanks for the speedy fix.
