### ISSUE TITLE
`violating_period': undefined method `to_i'

### ISSUE THREAD

**Issue by xiaket** [stelligent/cfn_nag#441]
We are using the latest version of cfn-nag to check our cfn templates, the error mentioned in the title comes up this morning and I believe this is related to this commit: https://github.com/stelligent/cfn_nag/commit/f1fca0338382041395e0f9e0800c726f7cfb2f8e

The traceback looks like:

```
[2020-04-28T19:04:08Z] /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/custom_rules/RDSInstanceBackupRetentionPeriodRule.rb:32:in `violating_period': undefined method `to_i' for #<Hash:0x00005585964686d0> (NoMethodError)
--
  | [2020-04-28T19:04:08Z] Did you mean?  to_s
  | [2020-04-28T19:04:08Z]                to_a
  | [2020-04-28T19:04:08Z]                to_h
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/custom_rules/RDSInstanceBackupRetentionPeriodRule.rb:23:in `block in audit_impl'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/custom_rules/RDSInstanceBackupRetentionPeriodRule.rb:22:in `select'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/custom_rules/RDSInstanceBackupRetentionPeriodRule.rb:22:in `audit_impl'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/custom_rules/base.rb:19:in `audit'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/custom_rule_loader.rb:70:in `block in filter_rule_classes'
  | [2020-04-28T19:04:08Z] 	from /usr/local/lib/ruby/2.5.0/set.rb:338:in `each_key'
  | [2020-04-28T19:04:08Z] 	from /usr/local/lib/ruby/2.5.0/set.rb:338:in `each'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/custom_rule_loader.rb:63:in `filter_rule_classes'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/custom_rule_loader.rb:54:in `execute_custom_rules'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/cfn_nag.rb:90:in `audit'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/cfn_nag_executor.rb:59:in `scan_file'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/cfn_nag_executor.rb:38:in `execute_file_or_piped_scan'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/lib/cfn-nag/cfn_nag_executor.rb:29:in `scan'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/gems/cfn-nag-0.5.48/bin/cfn_nag:11:in `<top (required)>'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/bin/cfn_nag:23:in `load'
  | [2020-04-28T19:04:08Z] 	from /usr/local/bundle/bin/cfn_nag:23:in `<main>'
  | [2020-04-28T19:04:08Z] File (template/ironman-02-data.yml) is not ok ❌
```

**Comment by erickascic** [comment]
oi @xiaket thx for reporting.  fix coming out momentarily

**Comment by mike-asm** [comment]
I've verified that this is due to using `!FindInMap` to provide the value.
If I hard code the value to an integer, the tests run through.

**Comment by erickascic** [comment]
@xiaket give 0.5.50 a go.  should fix your issue.  the pipeline is red because of some annoyance with generating the Docker image - not the underlying gem

**Comment by xiaket** [comment]
Thanks, it worked!

```
{PLATFORMS-4299!? ~/.xia/sha/bit/ironman}cfn_nag --version
0.5.50
{PLATFORMS-4299!? ~/.xia/sha/bit/ironman}cfn_nag template/ironman-02-data.yml
------------------------------------------------------------
template/ironman-02-data.yml
------------------------------------------------------------
Failures count: 0
Warnings count: 0
```
