### ISSUE TITLE
cannot load cfn-model

### ISSUE THREAD

**Issue by jleiber** [stelligent/cfn_nag#485]
I get this output when I attempt to run a cfn_nag_scan:

```
Traceback (most recent call last):
	12: from /usr/local/bin/cfn_nag_scan:23:in `<main>'
	11: from /usr/local/bin/cfn_nag_scan:23:in `load'
	10: from /Users/josephleiber/.gem/ruby/2.6.0/gems/cfn-nag-0.6.7/bin/cfn_nag_scan:4:in `<top (required)>'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /Users/josephleiber/.gem/ruby/2.6.0/gems/cfn-nag-0.6.7/lib/cfn-nag.rb:3:in `<top (required)>'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /Users/josephleiber/.gem/ruby/2.6.0/gems/cfn-nag-0.6.7/lib/cfn-nag/cfn_nag.rb:3:in `<top (required)>'
	 3: from /Users/josephleiber/.gem/ruby/2.6.0/gems/cfn-nag-0.6.7/lib/cfn-nag/cfn_nag.rb:3:in `require_relative'
	 2: from /Users/josephleiber/.gem/ruby/2.6.0/gems/cfn-nag-0.6.7/lib/cfn-nag/custom_rule_loader.rb:3:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- cfn-model (LoadError)
```

My environment:

```
Josephs-MacBook-Pro-2:~ josephleiber$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
Josephs-MacBook-Pro-2:~ josephleiber$ bundle -v
Bundler version 2.1.2
Josephs-MacBook-Pro-2:~ josephleiber$ gem -v
3.1.2
```

**Comment by arothian** [comment]
Hi @jleiber , this looks like potentially a local install issue. Can you verify that the `cfn-model` gem is installed? This is a dependency for running cfn_nag.

`gem list cfn-model`

**Comment by arothian** [comment]
Closing this issue. Let us know if this is continuing to cause problems and we'll be happy to help.
