### ISSUE TITLE
input path error at GitHub Actions

### ISSUE THREAD

**Issue by FY0323** [stelligent/cfn_nag#486]
# What's happened?

I tried to use cfn-nag in GitHub Actions, but the following error log is returned;

```
Run stelligent/cfn_nag@master
  with:
    input_path: cfn
    extra_args: --print-suppression
/usr/bin/docker run --name b3ac6da6c6f3c97ae4bd1befbde8314a4d089_24423a --label 3b3ac6 --workdir /github/workspace --rm -e INPUT_INPUT_PATH -e INPUT_EXTRA_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/github-cfn-test/github-cfn-test":"/github/workspace" 3b3ac6:da6c6f3c97ae4bd1befbde8314a4d089
/usr/local/bundle/gems/cfn-nag-0.6.7/lib/cfn-nag/template_discovery.rb:14:in `discover_templates': cfn is not a proper path (RuntimeError)
	from /usr/local/bundle/gems/cfn-nag-0.6.7/lib/cfn-nag/cfn_nag.rb:61:in `audit_aggregate_across_files'
	from /usr/local/bundle/gems/cfn-nag-0.6.7/lib/cfn-nag/cfn_nag.rb:34:in `audit_aggregate_across_files_and_render_results'
	from /usr/local/bundle/gems/cfn-nag-0.6.7/lib/cfn-nag/cfn_nag_executor.rb:50:in `execute_aggregate_scan'
	from /usr/local/bundle/gems/cfn-nag-0.6.7/lib/cfn-nag/cfn_nag_executor.rb:30:in `scan'
	from /usr/local/bundle/gems/cfn-nag-0.6.7/bin/cfn_nag_scan:11:in `<top (required)>'
	from /usr/local/bundle/bin/cfn_nag_scan:23:in `load'
	from /usr/local/bundle/bin/cfn_nag_scan:23:in `<main>'
```

The part of cfn-nag in workflow file is as follows;

```
  cfn-nag:
    runs-on: ubuntu-latest
    steps:
    - name: execute cfn_nag
      uses: stelligent/cfn_nag@master
      with:
        input_path: cfn
```

The error showed the wrong settings of input path. But, at local environment, I checked that ```cfn_nag_scan``` command succeeded.

```
root@ubuntu:~# cfn_nag_scan --input-path cfn
------------------------------------------------------------
cfn/cfn.yml
------------------------------------------------------------------------------------------------------------------------
| WARN W60
|
| Resources: ["TutorialVPC"]
| Line Numbers: [7]
|
| VPC should have a flow log attached

Failures count: 0
Warnings count: 1
root@ubuntu:~#
```

I also tested same scenario by install of cfn-nag packages using ```gem``` command, but the result is same.

```
  cfn-nag:
    runs-on: ubuntu-latest
    steps:
    - name: install cfn_nag
      run: sudo gem install cfn-nag
    - name: execute cfn_nag
      run: cfn_nag_scan --input-path cfn
```

```
Run cfn_nag_scan --input-path cfn
  cfn_nag_scan --input-path cfn
  shell: /bin/bash -e {0}
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/var/lib/gems/2.5.0/gems/cfn-nag-0.6.7/lib/cfn-nag/template_discovery.rb:14:in `discover_templates': cfn is not a proper path (RuntimeError)
	from /var/lib/gems/2.5.0/gems/cfn-nag-0.6.7/lib/cfn-nag/cfn_nag.rb:61:in `audit_aggregate_across_files'
	from /var/lib/gems/2.5.0/gems/cfn-nag-0.6.7/lib/cfn-nag/cfn_nag.rb:34:in `audit_aggregate_across_files_and_render_results'
	from /var/lib/gems/2.5.0/gems/cfn-nag-0.6.7/lib/cfn-nag/cfn_nag_executor.rb:50:in `execute_aggregate_scan'
	from /var/lib/gems/2.5.0/gems/cfn-nag-0.6.7/lib/cfn-nag/cfn_nag_executor.rb:30:in `scan'
	from /var/lib/gems/2.5.0/gems/cfn-nag-0.6.7/bin/cfn_nag_scan:11:in `<top (required)>'
	from /usr/local/bin/cfn_nag_scan:23:in `load'
	from /usr/local/bin/cfn_nag_scan:23:in `<main>'
##[error]Process completed with exit code 1.
```

# More information

My Github Repository's hierarchical structure is following;

```
./
|
|--README.md
|--template.yml
|--cfn
|   |
|   |--template.yml
|
|--.github
    |
    |--workflows
       |
       |--deploy.yml
```

My cfn and workflow templates are following;

```cfn template
Parameters:
  Environment:
    Type: String

Resources:
  TutorialVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: cfn-cicd
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Test
          Value: GitHub Actions
```

```workflow template
name: CloudFormation Deploy Development
on:
  push:
    branches:
      - dev
    paths:
      - '**.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Python Version
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install cfn-python-lint
      run: pip install --no-cache-dir cfn-lint
    - name: Execute Lint Check
      run: cfn-lint template.yml

  cfn-nag:
    runs-on: ubuntu-latest
    steps:
    - name: execute cfn_nag
      uses: stelligent/cfn_nag@master
      with:
        input_path: cfn

  build:
    needs: [lint, cfn-nag]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Deploy Cloudformation Stack
      env:
        STACK_NAME: createvpc-dev
        TEMPLATE_NAME: template.yml
      run: |
        aws cloudformation deploy \
          --stack-name ${STACK_NAME} \
          --template-file ${TEMPLATE_NAME} \
          --parameter-overrides Environment=development \
          --no-fail-on-empty-changeset
```

**Comment by FY0323** [comment]
I forget to add ```actions/checkout@v2``` in ```cfn-nag``` step. The workflow is now succeeded, and this issue is closed.
