### ISSUE TITLE
stack trace when YAML dict passed instead of string

### ISSUE THREAD

**Issue by oshaughnessy** [stelligent/cfn_nag#89]
I had a CFN template with an entry parsed as a dict instead of a string:

```
Mappings:
    MyMap:
        MyKey: Ref: AWS::NoValue
```

when it should have looked like this:

```
Mappings:
    MyMap:
        MyKey: !Ref: AWS::NoValue
```

I think the YAML parser is processing that as a dict because of the colons after `MyKey:`.

cfn_nag gave me a stack trace with the actual error buried inside:

```
Running command cfn_nag_scan -p .cfn_nag -i CloudFormation
/usr/local/lib/ruby/gems/2.3.0/gems/cfn-model-0.1.11/lib/cfn-model/parser/cfn_parser.rb:121: warning: already initialized constant ServiceCatalogProduct
/usr/local/lib/ruby/gems/2.3.0/gems/cfn-model-0.1.11/lib/cfn-model/parser/cfn_parser.rb:121: warning: previous definition of ServiceCatalogProduct was here
/usr/local/lib/ruby/2.3.0/psych.rb:377:in `parse': (<unknown>): mapping values are not allowed in this context at line 57 column 22 (Psych::SyntaxError)
from /usr/local/lib/ruby/2.3.0/psych.rb:377:in `parse_stream'
from /usr/local/lib/ruby/2.3.0/psych.rb:325:in `parse'
from /usr/local/lib/ruby/2.3.0/psych.rb:252:in `load'
from /usr/local/lib/ruby/gems/2.3.0/gems/cfn-model-0.1.11/lib/cfn-model/validator/resource_type_validator.rb:6:in `validate'
from /usr/local/lib/ruby/gems/2.3.0/gems/cfn-model-0.1.11/lib/cfn-model/validator/schema_generator.rb:15:in `generate'
from /usr/local/lib/ruby/gems/2.3.0/gems/cfn-model-0.1.11/lib/cfn-model/validator/cloudformation_validator.rb:6:in `validate'
from /usr/local/lib/ruby/gems/2.3.0/gems/cfn-model-0.1.11/lib/cfn-model/parser/cfn_parser.rb:80:in `pre_validate_model'
from /usr/local/lib/ruby/gems/2.3.0/gems/cfn-model-0.1.11/lib/cfn-model/parser/cfn_parser.rb:33:in `parse'
from /usr/local/lib/ruby/gems/2.3.0/gems/cfn-nag-0.3.11/lib/cfn-nag/cfn_nag.rb:64:in `audit'
from /usr/local/lib/ruby/gems/2.3.0/gems/cfn-nag-0.3.11/lib/cfn-nag/cfn_nag.rb:48:in `block in audit_aggregate_across_files'
from /usr/local/lib/ruby/gems/2.3.0/gems/cfn-nag-0.3.11/lib/cfn-nag/cfn_nag.rb:45:in `each'
from /usr/local/lib/ruby/gems/2.3.0/gems/cfn-nag-0.3.11/lib/cfn-nag/cfn_nag.rb:45:in `audit_aggregate_across_files'
from /usr/local/lib/ruby/gems/2.3.0/gems/cfn-nag-0.3.11/lib/cfn-nag/cfn_nag.rb:29:in `audit_aggregate_across_files_and_render_results'
from /usr/local/lib/ruby/gems/2.3.0/gems/cfn-nag-0.3.11/bin/cfn_nag_scan:32:in `<top (required)>'
from /usr/local/bin/cfn_nag_scan:23:in `load'
from /usr/local/bin/cfn_nag_scan:23:in `<main>'

Command did not exit successfully cfn_nag_scan -p .cfn_nag -i CloudFormation exit status 1
```

To me, the only useful part of that is at line 3:

> mapping values are not allowed in this context at line 57 column 22 (Psych::SyntaxError)

I don't know how feasible it is, but I think it would be great if cfn-nag could catch an error like that and give me a warning that's easier to identify.

Thanks.

**Comment by erickascic** [comment]
This turned out to be fairly easy to fix.  There was a "throttle" point for parser errors but that bit of processing didn't include rescuing exception from the Psych parser.  Just had to add that to the rescue list.

The behavior is:

Given a YAML/JSON file with invalid syntax
When cfn-nag scans the file
Then it returns a failing violation with id FATAL that includes a description of the syntax error.

like so:
        {
          "id": "FATAL",
          "type": "FAIL",
          "message": "(<unknown>): mapping values are not allowed in this context at line 3 column 15",
          "logical_resource_ids": null
        }
Fix is in 0.3.13
